import type { Locale } from "@/lib/i18n";

export interface BlogPost {
  id: string;
  title: string;
  slug: string;
  content: string;
  language: Locale;
  seoTitle: string;
  seoDescription: string;
  categoryId?: string;
  categories?: Array<{
    id: string;
    key: string;
    name: string;
    slug?: string;
  }>;
  featuredImage?: string;
  keywords: string[];
  autoGenerated: boolean;
  publishedAt?: string;
  createdAt: string;
}
