import type { BlogPost } from "@/lib/blogTypes";
import type { Locale } from "@/lib/i18n";

type BlogCategory = {
  id: string;
  key: string;
  name: string;
  slug: string;
};

const BLOG_CATEGORIES: Record<string, BlogCategory> = {
  sanayi: { id: "sanayi", key: "sanayi", name: "Sanayi", slug: "sanayi" },
  lojistik: { id: "lojistik", key: "lojistik", name: "Lojistik", slug: "lojistik" },
  tarim: { id: "tarim", key: "tarim", name: "Tarim", slug: "tarim" },
  turizm: { id: "turizm", key: "turizm", name: "Turizm", slug: "turizm" },
  ticari: { id: "ticari", key: "ticari", name: "Ticari", slug: "ticari" },
};

function category(id: keyof typeof BLOG_CATEGORIES) {
  return BLOG_CATEGORIES[id];
}

function post(input: {
  id: string;
  title: string;
  slug: string;
  categoryId: keyof typeof BLOG_CATEGORIES;
  featuredImage: string;
  seoDescription: string;
  keywords: string[];
  publishedAt: string;
  content: string;
}): BlogPost {
  const selectedCategory = category(input.categoryId);

  return {
    id: input.id,
    title: input.title,
    slug: input.slug,
    content: input.content,
    language: "tr",
    seoTitle: input.title,
    seoDescription: input.seoDescription,
    categoryId: selectedCategory.id,
    categories: [selectedCategory],
    featuredImage: input.featuredImage,
    keywords: input.keywords,
    autoGenerated: false,
    publishedAt: input.publishedAt,
    createdAt: input.publishedAt,
  };
}

const STATIC_POSTS_TR: BlogPost[] = [
  post({
    id: "blog-tr-001",
    title: "Sanayi Tesisleri İçin GES Yatırım Rehberi 2026",
    slug: "sanayi-tesisleri-icin-ges-yatırım-rehberi-2026",
    categoryId: "sanayi",
    featuredImage: "/sistemlerimiz.webp",
    seoDescription:
      "Fabrika çatılarında güneş enerjisi sistemi kurulumu, maliyet analizi ve geri ödeme süreleri hakkinda kapsamli rehber.",
    keywords: ["GES", "Sanayi", "Yatırım"],
    publishedAt: "2026-03-28T10:00:00.000Z",
    content: `
## Neden Sanayi Tesisleri İçin GES?
Sanayi tesisleri, yüksek elektrik tüketimi ve genis çatı alanları ile güneş enerjisi yatırımlarının en verimli şekilde değerlendirilebildiği yapilardir. Türkiye'de lisanssız üretim sınırının **5 MW'a** çıkarılmasıyla birlikte orta ve büyük ölçekli sanayi tesisleri için çatı GES artik opsiyonel bir yatırım olmaktan çıkıp **stratejik bir zorunluluk** hâline gelmiştir.

Gündüz agirlikli üretim profili, solar üretim egrisiyle doğrudan örtüşür. Bu örtüşme, üretilen enerjinin **%90'in üzerinde öz tüketime** dönmesini sağlar ve sebekeye satis yerine kendi ihtiyacini karsilama modelini ekonomik kilar.

> "Sanayi için GES artik bir "yeşil pazarlama" aracı değil; doğrudan bilançoya yansıyan bir **rekabet avantajıdır**."

## Maliyet Analizi ve ROI
Tipik bir **1.000 kWp** (1 MWp) kurulum için toplam yatırım tutarı — panel, inverter, montaj, kablolama, SCADA ve devreye alma dahil — 2026 fiyatlarıyla yaklaşık **18–22 milyon TL** aralığındadır. Yıllık üretim beklentisi coğrafi konuma göre değişmekle birlikte:

- İç Anadolu / Güneydoğu: 1.500.000–1.650.000 kWh
- Ege / Akdeniz: 1.450.000–1.600.000 kWh
- Marmara / Karadeniz: 1.300.000–1.450.000 kWh

Birim elektrik tasarrufu kWh basina **3,20–4,10 TL** arasında değerlendirildiğinde, tesislerin çoğunluğu yatırımı **4 ila 6 yılda** geri ödemektedir. Panel garantileri 25–30 yıl olduğundan, yatırımın geri kalan 20 yılı net kazanca dönüşür.

## Teknik Gereksinimler
Projelendirme öncesi **saha etüdü** kritik önem tasir. Degerlendirilmesi gereken basliklar:

1. **çatı statigi**: Her mü için minimum 18 kg ek yük tasiyabilmeli.
2. **Gölgeleme haritasi**: Baca, klima dis ünitesi, komsu bina gölgelerinin yıllık etkisi simüle edilmeli.
3. **Yönelim ve egim**: Optimum güney yönelim, 25-35° egim.
4. **Kablo güzergâhı**: AC/DC izolasyon, yangin senaryosu uyumu.
5. **Inverter seçimi**: Avrupa verimliliği **%98+**, IP65, uzaktan izlenebilir.

Panel teknolojisinde **Tier-1 monokristal** üreticiler tercih edilmeli; 430–550 Wp arasi modüller 2026'da yaygin standart hâline gelmiştir. Bifacial paneller, beyaz zemin veya açık çatıda **%8–12 ek üretim** sağlar.

## Basvuru ve Izin Süreci
Lisanssiz üretim basvurusu dagitim sirketine yapilir ve süreç tipik olarak su adimlari izler:

1. **çağrı mektubu basvurusu** — tesis bilgileri, tek hat semasi, sayaç verileri
2. **Baglanti anlaşması** — onayli proje, teminat mektubu
3. **Uygulama projesi onayi** — statik, elektrik ve yangin paftalari
4. **Kurulum** — 2–4 ay arasi saha ısı
5. **Geçici kabul ve devreye alma** — performans testleri (**PR = %80**)
6. **Kesin kabul** — 12 aylik izleme sonrasi

Tüm süreç ortalama **6–9 ay** sürer. EPDK, TEIAS ve belediye paralel yürütülür; dogru planlamayla bu süre kısaltılabilir.
    `.trim(),
  }),
  post({
    id: "blog-tr-002",
    title: "Depo ve Lojistik Merkezi çatılarında Solar Enerji",
    slug: "depo-ve-lojistik-merkezi-çatılarında-solar-enerji",
    categoryId: "lojistik",
    featuredImage: "/blog-back.webp",
    seoDescription:
      "Genis çatı alanlarina sahip lojistik tesislerinde enerji maliyetlerini düşürmenin en etkili yolu.",
    keywords: ["Lojistik", "çatı GES", "Solar Enerji"],
    publishedAt: "2026-03-22T10:00:00.000Z",
    content: `
## Lojistik Yapilar Neden Uygun?
Depo ve lojistik merkezleri genis, gölgesiz çatı alanları sayesinde yüksek verimli güneş enerji uygulamalari için güçlü bir potansiyel tasir.

## Operasyonel Fayda
Gündüz yük profili ile güneş üretiminin çakışması, enerji faturasini düşürürken operasyonel öngörülebilirlik sağlar.

## Uygulama Kriterleri
çatı kaplamasi, statik durum, yangin senaryosu ve inverter yerlesimi proje tasariminda öne çıkan basliklardir.
    `.trim(),
  }),
  post({
    id: "blog-tr-003",
    title: "Tarimsal Sulama Sistemlerinde Güneş Enerjisi Kullanimi",
    slug: "tarimsal-sulama-sistemlerinde-gunes-enerjisi-kullanimi",
    categoryId: "tarim",
    featuredImage: "/referanslar.webp",
    seoDescription:
      "Solar pompa sistemleri ile sulama maliyetlerini düşürmek isteyen isletmeler için pratik kullanim rehberi.",
    keywords: ["Tarim", "Sulama", "Solar Pompa"],
    publishedAt: "2026-03-15T10:00:00.000Z",
    content: `
## Sulamada Enerji Maliyeti
Tarimsal üretimde sulama maliyeti önemli bir yük olusturur. Güneş enerjili pompa sistemleri bu gideri önemli ölçüde azaltabilir.

## Sistem Seçimi
Pompa gücü, günlük su ihtiyaci ve sulama saatleri dogru belirlenmeden yapılan seçimler verim kaybina yol açar.

## Saha Uygulamasi
Dogru panel dizisi ve sürücü konfigürasyonu ile özellikle kirsal alanlarda güvenilir bir çözüm elde edilir.
    `.trim(),
  }),
  post({
    id: "blog-tr-004",
    title: "Otel ve Tatil Köylerinde Enerji Bagimsizligi",
    slug: "otel-ve-tatil-koylerinde-enerji-bagimsizligi",
    categoryId: "turizm",
    featuredImage: "/faaliyet-alanları.webp",
    seoDescription:
      "Turizm sektöründe güneş enerjisi yatırımlarının geri dönüş süreleri ve tüketim optimizasyonu.",
    keywords: ["Turizm", "Otel", "Enerji Bagimsizligi"],
    publishedAt: "2026-03-10T10:00:00.000Z",
    content: `
## Turizmde Tüketim Profili
Oteller ve tatil köyleri, yaz sezonunda yogunlasan gündüz tüketimleri nedeniyle güneş enerjisi yatırımı için **sektörel açıdan en avantajli yapılar** arasında yer alir. Klima, havuz pompalari, çamaşırhane, mutfak ekipmanlari ve aydinlatma gibi yükler; gün dogumundan gün batimina kadar sürekli çalışır ve güneş üretim egrisiyle neredeyse **birebir örtüşür**.

Türkiye'nin güney sahillerinde faaliyet gösteren bir 5 yildizli otel için yıllık elektrik tüketimi ortalama **3.500.000–4.500.000 kWh** arasında değişir. Bu tüketimin **%55–65'i** gündüz saatlerinde (09:00–19:00) gerçekleşir; bu pencere solar üretim penceresi ile doğrudan örtüşür.

> "Turizm yatırımcıları için çatı GES artik 'iyi olurdu' kategorisinden 'olmazsa olmaz' kategorisine geçti. Banka finansman süreçlerinde bile ÇED raporlarinin bir parçası hâline geldi."

## Finansal Denge ve ROI
Otellerin çatı alanı, bahçe ve otopark gölgelikleri birlikte değerlendirildiğinde tipik bir **500–1.200 kWp** arasi sistem kurulabilir. 2026 fiyatlarıyla böyle bir sistem için yatırım maliyeti **10–24 milyon TL** aralığındadır. Yıllık üretim beklentisi **800.000–2.000.000 kWh** arasında değişir.

Elektrik birim fiyatının (kWh basina **3,50–4,50 TL** ticari tarifede) ve CO2 indirimi katkılarının dikkate alinmasiyla geri ödeme süreleri su şekilde hesaplanir:

- **Akdeniz / Ege sahili (yüksek ışınım, uzun sezon)**: 3,5–5 yıl
- **Kuzey Ege / Istanbul yakini**: 4,5–6 yıl
- **Karadeniz (sezon kısa, ışınım orta)**: 5,5–7 yıl

Panel garantisi 25–30 yıl oldugu için yatırımın geri kalan **19–24 yıllık kısmi** doğrudan kâra dönüşür. Orta ölçekli bir otel için bu rakam **80–200 milyon TL net kazanç** anlamina gelir.

## Kurulum Senaryolari
Turizm tesislerinde üç farklı kurulum yaklasimi bulunur:

1. **Klasik çatı GES** — ana bina, restoran ve spa çatıları üzerinde 50–400 kWp arasi modüler sistemler. En hizli geri ödeme.
2. **Otopark gölgelik GES** — hem misafir konforu (gölge + sarj) hem üretim sağlar. 100–600 kWp.
3. **Hibrit sistem (GES + batarya)** — sebeke kalitesi düşük veya ada bölgelerinde kesintisiz enerji. 24 saat kesintisiz.

## Teknik Kriterler
Turizm tesisleri için dogru sistem tasariminda dikkat edilmesi gereken basliklar:

- **çatı türü**: Kiremit, sandviç panel, beton — her biri farklı montaj sistemi gerektirir.
- **Statik analiz**: Ek yük **18–22 kg/mü** arasında olmali; rüzgâr yükü sahilde **125 km/saat**'e kadar hesaplanir.
- **Estetik**: Misafir görüş hattindan panelin görünmemesi tercih edilir; mat panel ve siyah çerçeveli modüller bu amaçla seçilir.
- **Yangin yönetmeliği**: Oteller **yüksek yapi sinifi**nda değerlendirilir, DC izolasyon cihazlari ve modül-seviye izleme (MLPE) zorunludur.
- **Gürültü**: Inverterler misafir odalarindan uzak, teknik odalarda konumlandirilir.

## Pazarlama ve Marka Degeri
Sürdürülebilirlik turist profilinin karar kriterlerinde **ilk üç sirada** yer aliyor. özellikle Kuzey Avrupa pazarinda (%74' iklim bilinçli) GES sertifikasi olan otellerin fiyat esnekligi **%10–15 daha yüksek**.

- **Green Key, Travelife, EarthCheck** gibi sertifikalar GES'li tesislerde kolay elde edilir.
- Booking.com ve TripAdvisor'da **Sürdürülebilir Otel rozetleri** ayri filtre ile öne çıkar.
- Uluslararasi tur operatörleri (TUI, Thomas Cook varisleri, Der Touristik) tedarikçi seçimlerinde GES'i belirleyici kriter olarak değerlendiriyor.

## Operasyonel Avantajlar
çatı GES sadece finansal bir yatırım değil, operasyonel bir iyilestirmedir:

1. **Elektrik faturasinda öngörülebilirlik** — üretimin **%70–85'i** öz tüketime döner, faturada sok artislar yasanmaz.
2. **Kesinti dayanikliligi** — batarya takviyesi ile 4–8 saat kesintisiz hizmet.
3. **Iklimlendirme destegi** — panellerin çatıda olusturdugu gölge klima yükünü **%8–12** azaltir.
4. **Elektrikli araç misafir sarji** — otopark GES ile ek hizmet ve gelir kalemi.
5. **Karbon raporlamasi** — CBAM, ESG ve IFRS S2 gereklilikleri için hazir veri akisi.

## Basvuru ve Uygulama Süreci
Turizm isletmelerinde tipik süreç:

1. **Saha etüdü** (1–2 hafta) — çatı alanı, gölgeleme, statik.
2. **ön tasarim ve fizibilite** (2 hafta) — kurulu güç, yıllık üretim, ROI.
3. **Dagitim sirketi basvurusu** (4–8 hafta) — çağrı mektubu + baglanti anlaşması.
4. **Proje onayi** (3–6 hafta) — elektrik, statik, yangin paftalari.
5. **Kurulum** (6–12 hafta) — sezon disinda yapilmasi tercih edilir.
6. **Test ve devreye alma** (2–3 hafta) — performans orani (**PR = %80**) testi.

Toplam süreç sezon disinda planlandiginda **4–6 ay** içinde tamamlanir. Kis aylarinda baslatilan projeler sezon açılmadan faaliyete geçer.

## Sik Sorulan Sorular
**Panel ömrü kaç yıl?** Tier-1 monokristal paneller için **25–30 yıl** performans garantisi standart hâle gelmiştir; 25. yilin sonunda panel verimi **%85 üzerinde** kalir.

**Bakim maliyeti yüksek mi?** Yilda **bir kez yikama** ve **iki kez elektriksel kontrol** yeterlidir. Ortalama bakim maliyeti kurulum bedelinin **%0,8–1,2'si**.

**Dolu, kar veya firtina panelleri zarar verir mi?** Tier-1 paneller **IEC 61215** standardinda, **25 mm doluya** ve **2400 Pa** rüzgâr yüküne karsi sertifikalidir.

**Sezon disinda enerji ne olur?** Fazla üretim sebekeye satilir veya gelecek fatura döneminde **netleme** ile düşülür.

## Sonuç
Turizm sektörü, çatı GES yatırımı için dogal yapısı geregi **en verimli** sektörlerden biridir. Hizli geri dönüş süreleri, operasyonel avantajlar, sertifikasyon kolayligi ve misafir deneyimine doğrudan katkı; bu yatırımı **opsiyonel** olmaktan çıkarıp **stratejik zorunluluk** hâline getirmistir.

Yüksek sezon tüketim pikleri, solar üretim egrisiyle örtüştüğünde öz tüketim orani **%85+** seviyesine çıkar. Bu da otellerin maliyet baskisini azaltirken misafir memnuniyetini artiran bir sistemin temel tasidir.
    `.trim(),
  }),
  post({
    id: "blog-tr-005",
    title: "AVM ve Ticari Binalarda çatı GES Uygulamalari",
    slug: "avm-ve-ticari-binalarda-çatı-ges-uygulamalari",
    categoryId: "ticari",
    featuredImage: "/center-villa-dark.webp",
    seoDescription:
      "Ticari yapilarda çatı GES planlamasi, izin süreçleri ve yatırım geri dönüş dengesine bakis.",
    keywords: ["Ticari", "AVM", "çatı GES"],
    publishedAt: "2026-03-05T10:00:00.000Z",
    content: `
## Ticari Yapilar İçin Uygun Senaryo
AVM ve ofis yapilarinda elektrik yükü gün içine yayilir; bu durum çatı GES ile yüksek öz tüketim orani yaratir.

## Proje Tasarimi
Yük profili, çatı alanı, tasiyici sistem ve dagitim sirketi prosedürleri birlikte ele alinmalidir.

## Uygulama Sonrasi
Izleme, bakim ve performans raporlamasi yatırımın uzun ömürlü olmasini sağlar.
    `.trim(),
  }),
  // ---- Sanayi ek yazılar ----
  post({
    id: "blog-tr-006",
    title: "Tekstil Fabrikalarinda Enerji Verimliligi ve GES",
    slug: "tekstil-fabrikalarinda-enerji-verimliliği-ve-ges",
    categoryId: "sanayi",
    featuredImage: "/projects/gebze-elektronik-fabrikasi.webp",
    seoDescription: "Tekstil sektöründe yüksek elektrik tüketimini güneş enerjisi ile dengelemenin yollari.",
    keywords: ["Tekstil", "Sanayi", "Enerji Verimliligi"],
    publishedAt: "2026-02-28T10:00:00.000Z",
    content: `
## Tekstilde Enerji Yükü
Boyahane, örme ve dokuma hatlari sürekli yüksek elektrik tüketir. Gündüz üretim profili güneş ile mükemmel uyum sağlar.

## Uygulama Notlari
çatı statigi, buhar hatlari ve yangin yönetmeliği projelendirmede kritik basliklardir.

## Geri Dönüş
Tipik tekstil tesislerinde 4-5 yıl içinde yatırım kendisini amorti eder.
    `.trim(),
  }),
  post({
    id: "blog-tr-007",
    title: "Otomotiv Yan Sanayide çatı GES Uygulamalari",
    slug: "otomotiv-yan-sanayide-çatı-ges-uygulamalari",
    categoryId: "sanayi",
    featuredImage: "/sistemlerimiz.webp",
    seoDescription: "Otomotiv yan sanayinde sürdürülebilirlik raporlari ve GES yatırımlarının rolü.",
    keywords: ["Otomotiv", "Yan Sanayi", "Sürdürülebilirlik"],
    publishedAt: "2026-02-20T10:00:00.000Z",
    content: `
## OEM Talepleri
Ana üreticiler tedarikçilerinden karbon ayak izi raporu talep ediyor. GES, bu raporlarda en güçlü kalemdir.

## Pratik Uygulama
Pres, kaynak ve boyahanelerin gündüz tüketimi GES üretimi ile örtüşür.

## Sonuç
Yatırım hem maliyet hem de tedarik zinciri sürekliliği açısından stratejik önem tasir.
    `.trim(),
  }),
  post({
    id: "blog-tr-008",
    title: "Gida Isleme Tesislerinde Sogutma Yükü ve Solar",
    slug: "gida-isleme-tesislerinde-sogutma-yükü-ve-solar",
    categoryId: "sanayi",
    featuredImage: "/projects/manisa-tarim-kampusu.webp",
    seoDescription: "Soguk hava depolari ve gida isleme tesislerinde GES'in sogutma yüküne katkisi.",
    keywords: ["Gida", "Sogutma", "GES"],
    publishedAt: "2026-02-12T10:00:00.000Z",
    content: `
## Sogutma Yükü
Gida isleme tesislerinde sogutma, toplam enerjinin %40-60'ini olusturur. Güneş enerjisi tam olarak bu yükü besler.

## Mühendislik Yaklasimi
Kompresör profilleri ile inverter çıkışının uyumu yatırımın verimini doğrudan etkiler.

## Uzun Vadeli Etki
Soguk zincirin sürekliliği saglanirken isletme maliyetleri belirgin biçimde düşer.
    `.trim(),
  }),
  post({
    id: "blog-tr-009",
    title: "Metal Sanayide Karbon Ayak Izi Azaltimi",
    slug: "metal-sanayide-karbon-ayak-izi-azaltimi",
    categoryId: "sanayi",
    featuredImage: "/blog-back.webp",
    seoDescription: "Metal isleme tesislerinde GES yatırımı ile karbon ayak izi nasil azalir?",
    keywords: ["Metal", "Karbon", "Sanayi"],
    publishedAt: "2026-02-05T10:00:00.000Z",
    content: `
## Sektörel Baski
AB Sinirda Karbon Düzenlemesi (CBAM) metal ihracatçılarını doğrudan etkiliyor. GES, hizli ve ölçülebilir bir azaltim yöntemidir.

## Proje ölçeklendirme
Tesisin yıllık tüketimi baz alinarak dogru kurulu güç belirlenir.

## Raporlama
üretim verisi ISO 14064 ve CBAM raporlarina doğrudan entegre edilebilir.
    `.trim(),
  }),
  // ---- Lojistik ek yazılar ----
  post({
    id: "blog-tr-010",
    title: "Soguk Zincir Depolarinda Hibrit GES çözümleri",
    slug: "soguk-zincir-depolarinda-hibrit-ges-cozumleri",
    categoryId: "lojistik",
    featuredImage: "/projects/bursa-lojistik-merkezi.webp",
    seoDescription: "Soguk zincir lojistiginde kesintisiz enerji için hibrit GES + batarya mimarileri.",
    keywords: ["Soguk Zincir", "Hibrit", "Batarya"],
    publishedAt: "2026-01-28T10:00:00.000Z",
    content: `
## Kesintisizlik Sart
Soguk zincirde dakikalarla ölçülen kesintiler bile ürün kayiplarina yol açar. Hibrit GES + batarya bu riski düşürür.

## Sistem Boyutlandirma
Kompresör başlangıç akimlari ve günlük döngü sayisi batarya seçiminde belirleyici unsurlardir.

## ROI
Kesinti kaynakli ürün kayiplarinin önlenmesi yatırım geri dönüşünü ciddi biçimde hizlandirir.
    `.trim(),
  }),
  post({
    id: "blog-tr-011",
    title: "E-Ticaret Fulfillment Merkezlerinde Solar Strateji",
    slug: "eticaret-fulfillment-merkezlerinde-solar-strateji",
    categoryId: "lojistik",
    featuredImage: "/projects/izmir-lojistik-hub.webp",
    seoDescription: "E-ticaret depolarinda 7/24 operasyon için güneş enerjisi planlamasi.",
    keywords: ["E-Ticaret", "Fulfillment", "Lojistik"],
    publishedAt: "2026-01-20T10:00:00.000Z",
    content: `
## 7/24 Operasyon
Fulfillment merkezleri sürekli çalışır. Aydinlatma, konveyör ve robotik sistemler için güneş enerjisi sürekli ve ölçülebilir bir kaynaktir.

## çatı Verimi
Genis, gölgesiz ve modern çatılar metrekare basina yüksek üretim sağlar.

## Operasyonel Fayda
Enerji maliyetlerindeki düşüş kâr marjini doğrudan iyilestirir.
    `.trim(),
  }),
  post({
    id: "blog-tr-012",
    title: "Liman ve Aktarma Merkezlerinde GES Potansiyeli",
    slug: "liman-ve-aktarma-merkezlerinde-ges-potansiyeli",
    categoryId: "lojistik",
    featuredImage: "/referanslar.webp",
    seoDescription: "Liman alanlarinda genis sahalar ve agir makine yükü için GES çözümleri.",
    keywords: ["Liman", "Aktarma", "GES"],
    publishedAt: "2026-01-12T10:00:00.000Z",
    content: `
## Liman Yükleri
Vinç, konveyör ve aydinlatma sistemleri toplam tüketimde belirleyici unsurdur.

## Saha Avantaji
Liman sahalari genis ve gölgesizdir; gölgelik yapilarla GES uygulanabilir.

## Sürdürülebilirlik
Yeşil liman sertifikasyonlari için GES temel kriterler arasindadir.
    `.trim(),
  }),
  post({
    id: "blog-tr-013",
    title: "Filo Lojistiginde Sarj Istasyonu + GES Entegrasyonu",
    slug: "filo-lojistiginde-sarj-istasyonu-ges-entegrasyonu",
    categoryId: "lojistik",
    featuredImage: "/faaliyet-alanları.webp",
    seoDescription: "Elektrikli filolar için GES destekli sarj istasyonu mimarileri.",
    keywords: ["EV", "Sarj Istasyonu", "Filo"],
    publishedAt: "2026-01-05T10:00:00.000Z",
    content: `
## Filo Geçişi
Lojistik filolarinin elektriklesmesi sarj altyapisini zorunlu hale getiriyor.

## GES + Sarj
çatı GES + DC sarj kombinasyonu hem maliyet hem karbon avantaji sağlar.

## Akilli Yönetim
EMS ile sarj programlari üretim profiline göre optimize edilir.
    `.trim(),
  }),
  // ---- Tarim ek yazılar ----
  post({
    id: "blog-tr-014",
    title: "Sera Tariminda Güneş Enerjisi ve Iklimlendirme",
    slug: "sera-tariminda-gunes-enerjisi-ve-iklimlendirme",
    categoryId: "tarim",
    featuredImage: "/projects/manisa-tarim-kampusu.webp",
    seoDescription: "Modern seralarda iklimlendirme yükünü güneş enerjisi ile karsilamak.",
    keywords: ["Sera", "Tarim", "Iklimlendirme"],
    publishedAt: "2025-12-28T10:00:00.000Z",
    content: `
## Sera Yükü
Isitma, sogutma, fan ve sulama sistemleri seralarda yüksek elektrik gerektirir.

## Uygulama
çatı veya bitisik saha GES, yıl boyu tüketimi karsilayabilir.

## ürün Kalitesi
Stabil enerji kaynağı, ürün kalitesini de doğrudan iyilestirir.
    `.trim(),
  }),
  post({
    id: "blog-tr-015",
    title: "Süt çiftliklerinde Solar Pompa ve Sogutma",
    slug: "sut-ciftliklerinde-solar-pompa-ve-sogutma",
    categoryId: "tarim",
    featuredImage: "/referanslar.webp",
    seoDescription: "Süt üretim çiftliklerinde sagim ve sogutma yükleri için güneş enerjisi.",
    keywords: ["Süt", "çiftlik", "Solar"],
    publishedAt: "2025-12-20T10:00:00.000Z",
    content: `
## çiftlik Tüketimi
Sagim makineleri, süt sogutma tanklari ve sulama sistemleri yüksek enerji ister.

## Pratik çözüm
çatı GES + küçük batarya kombinasyonu süreklilik sağlar.

## Maliyet
Elektrik faturasinda kalici düşüş elde edilir.
    `.trim(),
  }),
  post({
    id: "blog-tr-016",
    title: "Bag ve Bahçelerde Off-Grid Sulama Sistemleri",
    slug: "bag-ve-bahcelerde-off-grid-sulama-sistemleri",
    categoryId: "tarim",
    featuredImage: "/blog-back.webp",
    seoDescription: "Sebeke erisimi olmayan bag ve bahçelerde off-grid solar sulama.",
    keywords: ["Off-Grid", "Sulama", "Bahçe"],
    publishedAt: "2025-12-12T10:00:00.000Z",
    content: `
## Sebekesiz Sahalar
Sebeke maliyeti yüksek olan bahçelerde off-grid solar sulama dogru çözümdür.

## Sistem Bilesenleri
Panel, sürücü, pompa ve depolama tanki dogru boyutlandirilmalidir.

## Avantaj
Yakit tasima ve jeneratör bakim masrafi tamamen ortadan kalkar.
    `.trim(),
  }),
  // ---- Turizm ek yazılar ----
  post({
    id: "blog-tr-017",
    title: "Butik Otellerde çatı GES ile Marka Degeri",
    slug: "butik-otellerde-çatı-ges-ile-marka-degeri",
    categoryId: "turizm",
    featuredImage: "/projects/antalya-resort-otel.webp",
    seoDescription: "Butik otellerde sürdürülebilirlik vurgusu ile marka degerini artirma.",
    keywords: ["Butik Otel", "GES", "Marka"],
    publishedAt: "2025-12-05T10:00:00.000Z",
    content: `
## Sürdürülebilirlik
Modern misafir profili çevre dostu isletmeleri tercih ediyor.

## GES Etkisi
Görünür panel kurulumu marka iletisiminde güçlü bir araştır.

## Maliyet Yönetimi
Sezonsal yüklerde elektrik gideri belirgin şekilde azalir.
    `.trim(),
  }),
  post({
    id: "blog-tr-018",
    title: "All-Inclusive Tesislerde Enerji Optimizasyonu",
    slug: "all-inclusive-tesislerde-enerji-optimizasyonu",
    categoryId: "turizm",
    featuredImage: "/center-villa-dark.webp",
    seoDescription: "Büyük otel tesislerinde mutfak, çamaşırhane ve havuz yükleri için GES.",
    keywords: ["Otel", "All-Inclusive", "Optimizasyon"],
    publishedAt: "2025-11-28T10:00:00.000Z",
    content: `
## Yüksek Tüketim
All-inclusive tesisler mutfak ve çamaşırhane yükleri ile yüksek elektrik harcar.

## GES Katkisi
çatı + otopark üstü GES kombinasyonu ile tüketim büyük oranda karsilanir.

## Ek Faydalar
Karbon raporlamasi ve uluslararasi sertifikasyon süreçlerine doğrudan katkı sağlar.
    `.trim(),
  }),
  post({
    id: "blog-tr-019",
    title: "Tatil Köyü Operasyonlarinda Hibrit Sistemler",
    slug: "tatil-koyu-operasyonlarinda-hibrit-sistemler",
    categoryId: "turizm",
    featuredImage: "/sistemlerimiz.webp",
    seoDescription: "Sebeke kalitesi düşük bölgelerdeki tatil köylerinde hibrit GES çözümleri.",
    keywords: ["Tatil Köyü", "Hibrit", "Turizm"],
    publishedAt: "2025-11-20T10:00:00.000Z",
    content: `
## Konum Riski
Sebeke kalitesi düşük tatil bölgelerinde kesintiler isletmeyi olumsuz etkiler.

## Hibrit çözüm
GES + batarya + jeneratör mimarisi bu riski sifirlar.

## Misafir Deneyimi
Kesintisiz hizmet doğrudan misafir memnuniyetini artirir.
    `.trim(),
  }),
  // ---- Ticari ek yazılar ----
  post({
    id: "blog-tr-020",
    title: "Plaza ve Ofis Binalarinda çatı GES Yatirimi",
    slug: "plaza-ve-ofis-binalarinda-çatı-ges-yatırımı",
    categoryId: "ticari",
    featuredImage: "/projects/ankara-ticari-kompleks.webp",
    seoDescription: "Plaza ve ofis binalarinda ortak alan tüketimini güneş enerjisi ile karsilamak.",
    keywords: ["Plaza", "Ofis", "çatı GES"],
    publishedAt: "2025-11-12T10:00:00.000Z",
    content: `
## Ofis Yükü
Klima, aydinlatma ve asansörler gündüz pikinde yogunlasir.

## GES üretimi
Bu pik, güneş üretimi ile mükemmel örtüşür.

## Yönetim Faydasi
Site/plaza yönetimi için ortak gider kalemleri belirgin biçimde azalir.
    `.trim(),
  }),
  post({
    id: "blog-tr-021",
    title: "Restoran Zincirlerinde Standart GES Paketi",
    slug: "restoran-zincirlerinde-standart-ges-paketi",
    categoryId: "ticari",
    featuredImage: "/blog-back.webp",
    seoDescription: "çoklu lokasyonlu restoran zincirleri için standart GES uygulama paketi.",
    keywords: ["Restoran", "Zincir", "GES"],
    publishedAt: "2025-11-05T10:00:00.000Z",
    content: `
## Zincir Avantaji
Aynı uygulama paketinin çoklu subelere yayilmasi maliyeti düşürür.

## Standart çözüm
Modüler tasarim ile her subede aynı verim hedefi yakalanir.

## Marka Iletisimi
Sürdürülebilirlik mesaji tüm subelerde tutarli şekilde verilir.
    `.trim(),
  }),
  post({
    id: "blog-tr-022",
    title: "Hastane ve Saglik Tesislerinde Hibrit GES",
    slug: "hastane-ve-sağlık-tesislerinde-hibrit-ges",
    categoryId: "ticari",
    featuredImage: "/faaliyet-alanları.webp",
    seoDescription: "Saglik tesislerinde kesintisiz enerji için hibrit GES çözümleri.",
    keywords: ["Hastane", "Saglik", "Hibrit"],
    publishedAt: "2025-10-28T10:00:00.000Z",
    content: `
## Kritik Yük
Hastanelerde enerji kesintisi hayati risk tasir.

## Hibrit Mimari
GES + batarya + jeneratör birlesimi, kesintisiz kritik yük güvencesi sağlar.

## Maliyet
Operasyonel elektrik gideri belirgin biçimde azalir.
    `.trim(),
  }),
];

function getPostsForLocale(locale: Locale): BlogPost[] {
  if (locale === "tr") {
    return [...STATIC_POSTS_TR].sort((a, b) => {
      const left = a.publishedAt ? new Date(a.publishedAt).getTime() : 0;
      const right = b.publishedAt ? new Date(b.publishedAt).getTime() : 0;
      return right - left;
    });
  }

  return [];
}

export const staticBlog = {
  async list(language: Locale, includeDrafts = true): Promise<BlogPost[]> {
    const posts = getPostsForLocale(language);
    if (includeDrafts) return posts;
    return posts.filter((p) => Boolean(p.publishedAt?.trim()));
  },

  async listForLocale(locale: Locale, includeDrafts = true): Promise<BlogPost[]> {
    return this.list(locale, includeDrafts);
  },

  async getBySlug(language: Locale, slug: string): Promise<BlogPost | null> {
    return getPostsForLocale(language).find((postItem) => postItem.slug === slug) ?? null;
  },

  async getBySlugForLocale(locale: Locale, slug: string): Promise<BlogPost | null> {
    return this.getBySlug(locale, slug);
  },
};
